package royale.RoyaleProtectionBlocks.Plugin.API.Exceptions;

import org.bukkit.command.CommandSender;

public abstract class RoyaleProtectionBlocksException extends Exception {

	private static final long serialVersionUID = -4919963018125957166L;

	public static enum Type {

		// @formatter:off
		
		// General exceptions
		
		PLAYERNOTFOUND,
		PLAYERNOTONLINE,
		
		// Protection exceptions
		
		PROTECTIONS_KICKDENIED,
		PROTECTIONS_KICKDENIEDBYPASS,
		PROTECTIONS_NOTENOUGHBALANCE,
		PROTECTIONS_BLOCKED,
		PROTECTIONS_PERMISSIONDENIED,
		PROTECTIONS_PRIORITYTOOHIGH,
		PROTECTIONS_PRIORITYBELOWZERO,
		PROTECTIONS_NOTFOUND,
		PROTECTIONS_BLOCKALREADYSHOWN,
		PROTECTIONS_BLOCKALREADYSHOWNMULTIPLE,
		PROTECTIONS_BLOCKALREADYHIDDEN,
		PROTECTIONS_BLOCKALREADYHIDDENMULTIPLE,
		PROTECTIONS_BLOCKOVERLAPING,
		PROTECTIONS_BLOCKOVERLAPINGMULTIPLE,
		PROTECTIONS_INCOMBAT,
		PROTECTIONS_UNKNOWN,
		PROTECTIONS_CANCELLED,
		PROTECTIONS_STOREUNAVAILABLE,
		PROTECTIONS_ALREADYPUBLIC,
		PROTECTIONS_ALREADYPRIVATE,
		
		PROTECTIONS_MERGE_DIFFERENTOWNERS,
		PROTECTIONS_MERGE_TOOFAR,
		PROTECTIONS_MERGE_SAMEPROTECTION,
		PROTECTIONS_MERGE_CHILDPROTECTION,
		PROTECTIONS_MERGE_ALREADYMERGED,
		PROTECTIONS_MERGE_NOTMERGED,
		PROTECTIONS_MERGE_DISABLED,
		
		// Protection delete exceptions

		PROTECTIONS_DELETE_NOTFOUND,
		PROTECTIONS_DELETE_ALREADYDELETED,
		PROTECTIONS_DELETE_PERMISSIONDENIED,
		PROTECTIONS_DELETE_SQL,
		PROTECTIONS_DELETE_UNKNOWN,
		PROTECTIONS_DELETE_CREATIONINPROGRESS,
		PROTECTIONS_DELETE_INPROGRESS,
		PROTECTIONS_DELETE_VIEWACTIVE,
		PROTECTIONS_DELETE_BLOCKSHOWN,
		PROTECTIONS_DELETE_CANCELLED,
		
		// Protection save exceptions

		PROTECTIONS_SAVE_ALREADYEXISTS,
		PROTECTIONS_SAVE_PERMISSIONDENIED,
		PROTECTIONS_SAVE_PERMISSIONDENIEDPROTECTIONBLOCK,
		PROTECTIONS_SAVE_NOTALLOWEDWORLD,
		PROTECTIONS_SAVE_BANNEDWORLD,
		PROTECTIONS_SAVE_MAXREACHED,
		PROTECTIONS_SAVE_BLOCKMAXREACHED,
		PROTECTIONS_SAVE_NAMEINUSE,
		PROTECTIONS_SAVE_NAMETOOLONG,
		PROTECTIONS_SAVE_OVERLAPS,
		PROTECTIONS_SAVE_OVERLAPSOFFSET,
		PROTECTIONS_SAVE_OVERLAPSWORLDGUARD,
		PROTECTIONS_SAVE_ALREADYOCCUPIED,
		PROTECTIONS_SAVE_RENAMEDENIED,
		PROTECTIONS_SAVE_SQL,
		PROTECTIONS_SAVE_UNKNOWN,
		PROTECTIONS_SAVE_NOVISIBLETEXT,
		PROTECTIONS_SAVE_INPROGRESS,
		PROTECTIONS_SAVE_CANCELLED,
		
		// Protection invitations exceptions

		PROTECTIONS_INVITATIONS_INVITATIONDENIED,
		PROTECTIONS_INVITATIONS_INVITATIONBLOCKED,
		PROTECTIONS_INVITATIONS_INVITATIONREQUIRED,
		PROTECTIONS_INVITATIONS_NOTINVITED,
		PROTECTIONS_INVITATIONS_NOTINVITEDYOURSELF,
		PROTECTIONS_INVITATIONS_ALREADYINVITED,
		PROTECTIONS_INVITATIONS_DELETESQL,
		PROTECTIONS_INVITATIONS_SAVESQL,
		PROTECTIONS_INVITATIONS_UNKNOWN,
		
		// Protection transfer exceptions

		PROTECTIONS_TRANSFER_SAMEOWNER,
		PROTECTIONS_TRANSFER_MAXREACHED,
		PROTECTIONS_TRANSFER_BLOCKMAXREACHED,
		
		// Protection transfer exceptions

		PROTECTIONS_PURCHASE_NOTFORSALE,
		PROTECTIONS_PURCHASE_ALREADYNOTFORSALE,
		PROTECTIONS_PURCHASE_SAMEOWNER,
		PROTECTIONS_PURCHASE_MAXREACHED,
		PROTECTIONS_PURCHASE_BLOCKMAXREACHED,
		PROTECTIONS_PURCHASE_NOTENOUGHBALANCE,
		
		// Protection flags exceptions
		
		PROTECTIONS_FLAGS_PERMISSIONDENIED,
		PROTECTIONS_FLAGS_NOTENOUGHBALANCE,
		PROTECTIONS_FLAGS_NOTFOUND,
		PROTECTIONS_FLAGS_UNKNOWN,
		
		// Protection settings exceptions
		
		PROTECTIONS_SETTINGS_PERMISSIONDENIED,
		PROTECTIONS_SETTINGS_NOTENOUGHBALANCE,
		PROTECTIONS_SETTINGS_NOTFOUND,
		PROTECTIONS_SETTINGS_INVALIDVALUE,
		PROTECTIONS_SETTINGS_INVALIDGROUP,
		PROTECTIONS_SETTINGS_SQL,
		PROTECTIONS_SETTINGS_UNKNOWN,
		
		// Protection settings exceptions
		
		PROTECTIONS_PERMISSIONS_PERMISSIONDENIED,
		PROTECTIONS_PERMISSIONS_NOTENOUGHBALANCE,
		PROTECTIONS_PERMISSIONS_NOTFOUND,
		PROTECTIONS_PERMISSIONS_NOTEDITABLE,
		PROTECTIONS_PERMISSIONS_NOTEDITABLEGROUP,
		PROTECTIONS_PERMISSIONS_INVALIDGROUP,
		PROTECTIONS_PERMISSIONS_SQL,
		PROTECTIONS_PERMISSIONS_UNKNOWN,

		// Protection teleport exceptions
		
		PROTECTIONS_TELEPORT_NOHOMESET,
		PROTECTIONS_TELEPORT_COOLDOWNACTIVE,
		PROTECTIONS_TELEPORT_UNKNOWN,
		PROTECTIONS_TELEPORT_CANCELLEDDUEMOVEMENT,
		PROTECTIONS_TELEPORT_UNSAFE,
		
		// Protection members delete exceptions
		
		PROTECTIONS_MEMBERS_DELETE_PERMISSIONDENIED,
		PROTECTIONS_MEMBERS_DELETE_SQL,
		PROTECTIONS_MEMBERS_DELETE_UNKNOWN,
		
		// Protection members save exceptions

		PROTECTIONS_MEMBERS_SAVE_UNAUTHORIZED,
		PROTECTIONS_MEMBERS_SAVE_CANNOTADDPROTECTIONOWNER,
		PROTECTIONS_MEMBERS_SAVE_CANNOTADDYOURSELF,
		PROTECTIONS_MEMBERS_SAVE_PERMISSIONDENIED,
		PROTECTIONS_MEMBERS_SAVE_SQL,
		PROTECTIONS_MEMBERS_SAVE_UNKNOWN,
		
		// Protection owners delete exceptions

		PROTECTIONS_OWNERS_DELETE_CANNOTDELETEPROTECTIONOWNER,
		PROTECTIONS_OWNERS_DELETE_PERMISSIONDENIED,
		PROTECTIONS_OWNERS_DELETE_SQL,
		PROTECTIONS_OWNERS_DELETE_UNKNOWN,
		
		// Protection owners save exceptions

		PROTECTIONS_OWNERS_SAVE_CANNOTADDPROTECTIONOWNER,
		PROTECTIONS_OWNERS_SAVE_CANNOTADDYOURSELF,
		PROTECTIONS_OWNERS_SAVE_PERMISSIONDENIED,
		PROTECTIONS_OWNERS_SAVE_SQL,
		PROTECTIONS_OWNERS_SAVE_UNKNOWN,
		
		// Protection banneds delete exceptions
		
		PROTECTIONS_BANNEDS_DELETE_PERMISSIONDENIED,
		PROTECTIONS_BANNEDS_DELETE_SQL,
		PROTECTIONS_BANNEDS_DELETE_UNKNOWN,
		
		// Protection banneds save exceptions

		PROTECTIONS_BANNEDS_SAVE_CANNOTADDPROTECTIONOWNER,
		PROTECTIONS_BANNEDS_SAVE_CANNOTADDYOURSELF,
		PROTECTIONS_BANNEDS_SAVE_PERMISSIONDENIED,
		PROTECTIONS_BANNEDS_SAVE_ALREADYBANNED,
		PROTECTIONS_BANNEDS_SAVE_SQL,
		PROTECTIONS_BANNEDS_SAVE_UNKNOWN,
		
		// Protection blocks exceptions
		
		PROTECTIONBLOCKS_GENERATEITEM,
		
		// Protection blocks delete exceptions
		
		PROTECTIONBLOCKS_DELETE_PERMISSIONDENIED,
		PROTECTIONBLOCKS_DELETE_SQL,
		PROTECTIONBLOCKS_DELETE_UNKNOWN,
		
		// Protection blocks save exceptions

		PROTECTIONBLOCKS_SAVE_IDINUSE,
		PROTECTIONBLOCKS_SAVE_IDNULL,
		PROTECTIONBLOCKS_SAVE_ITEMNULL,
		PROTECTIONBLOCKS_SAVE_PERMISSIONDENIED,
		PROTECTIONBLOCKS_SAVE_MAXIMUMACHIEVED,
		PROTECTIONBLOCKS_SAVE_SQL,
		PROTECTIONBLOCKS_SAVE_UNKNOWN,
		
		// Player guards exceptions
		PLAYERGUARDS_SQL,
		
		// Pending payments exceptions

		PENDINGPAYMENTS_LOAD_SQL,
		PENDINGPAYMENTS_SAVE_SQL,
		PENDINGPAYMENTS_DELETE_SQL
		
		// @formatter:on
	}

	public RoyaleProtectionBlocksException(String message) {
		super(message);
	}

	public RoyaleProtectionBlocksException(String message, Throwable exception) {
		super(message, exception);
	}

	public abstract Type getType();

	public abstract void sendError(CommandSender sender);

}
